### create
POST http://localhost:3000/calculations.json
Content-Type: application/json

{
  "champion_id_one": 1,
  "champion_id_two": 2,
  "ability_id": 1
}
### update
PATCH http://localhost:3000/calculations/1.json
Content-Type: application/json

{
  "champion_id_one": 1,
  "champion_id_two": 2,
  "ability_id": 1
}

### destroy - this id doesnt work anymore

DELETE http://localhost:3000/calculations/1.json
Content-Type: application/json